# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfafsjKhi_7tvY9xbHR7mLKRJzbbB1hp

PANDAS

to read the data
"""

pip install pandas

import pandas as pd

import numpy as np



df = pd.read_csv('/Churn_Modelling.csv')

df

df.head()

df.tail()

df.info()

df.describe()

df[10:13]

df[df.Age>50]

df['Age'].fillna(10)

df.pop('RowNumber')

df.head(5)

df['Balance'].apply(np.sqrt)

df['SqRoot']= df['Balance'].apply(np.sqrt)

df.head(5)

df['Age'].dropna()

s = pd.Series(list("abcdef"),index =[43,45,46,0,1,2])

s

s.loc[0]

s.iloc[0]

s= s.sort_index()
s

s.iloc[1]

s.iloc[4]

"""Matplotlib"""

pip install matplotlib

import matplotlib.pyplot as pit
import numpy as np

Data = {'year' : [1920,1930,1940,1950,1960,1970,1980,2000,2010,2020],
        'exchange_rate':[65,69,71,62,59,72,71,75,85,81]}

df = pd.DataFrame(Data,columns =['year','exchange_rate'])

df

df.plot(x='year', y ='exchange_rate',kind ='line')
pit.show()

df.plot(x='year', y ='exchange_rate',kind ='pie')
pit.show()

df.plot(x='year', y ='exchange_rate',kind ='barh')
pit.show()

df.plot(x='year', y ='exchange_rate',kind ='scatter')
pit.show()

pit.scatter(df['year'],df['exchange_rate'])
pit.show()

df

churn_df = pd.read_csv('/Churn_Modelling.csv')

churn_df

churn_df.Geography.value_counts().plot(kind ='barh')

churn_df.Geography.value_counts()

churn_df.Gender.value_counts().plot(kind ='pie')

df['Exited'].value_counts()

df['Exited'].value_counts().plot(kind ='bar')/len(df)*100

lable_ex = 'javascript','java','X','Y'
sizes = [12,13,14,34]
explode_labels = (0,0.2,0,0)
fig1,ax1 = pit.subplots()
ax1.pie(sizes,explode = explode_labels,labels = lable_ex,shadow = True,startangle = 120)
ax1.axis('equal')
pit.show()

"""Seaborn"""



"""Seaborn"""

pip install seaborn

import seaborn as sns

df = sns.load_dataset('iris')
df

print(df)

sns.kdeplot(df['sepal_length'] , shade = True)



sns.distplot(df['petal_length'])

for col in['sepal_length','sepal_width','petal_length']:
    sns.kdeplot(df[col], fill = True)

import pandas as pd

df = pd.DataFrame(Data)

sns.lineplot(x = df["year"] , y = df["exchange_rate"])

print("t"+"u")

import pandas as pd

list_r = pd.read_excel("/content/company_loist_R.xlsx")
list_j = pd.read_excel("/content/NITJSR_Recruiters.xlsx")

mearge_df = pd.merge(list_r,list_j,on = 'Company Name' , how = 'left' )

print(mearge_df)

mearge_df.to_excel("mearge_djf.xlsx", index=False)

"""EDA (Data cleaning)"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df= pd.read_csv("/content/Churn_Modelling.csv")

df.info()

print(df.isnull().sum())

u_df = df.dropna(axis=1)

u_df2 = df.dropna(axis = 0)

u_df.info()

df['Age'].mean()



df['Age'].median()

pip install -U scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Churn_Modelling.csv')

df.info()

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

df.head()

new_df = pd.DataFrame(df,columns = ['Age','Tenure'])

new_df.head(5)

new_df['Age'] = new_df['Age'].fillna(new_df['Age'].mean())

new_df

scaler = MinMaxScaler()



normalized_df = scaler.fit_transform(new_df)

print (normalized_df)

"""scaler = StandardScaler()
standardized_df = scaler.fit_transform(new_df)
print(standardized_df)
"""

import statsmodels

import matplotlib.ticker as mtick
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import seaborn as sns

teli_data_base = pd.read_csv('/content/Churn_Modelling.csv')

teli_data_base.info()

"""univariant analysis"""

telco_new = teli_data_base[['Geography', 'Gender', 'Exited']]

print(telco_new )

for i , predictor in enumerate(telco_new.drop(columns=['Exited'])):
    plt.figure()
    sns.countplot(data = telco_new,x=predictor,hue = 'Exited')

"""Bivarient Analysis"""

sns.histplot(x ="Gender", hue = "Geography" , data = telco_new, stat ="count" , multiple ="dodge")

"""Feature encoding"""

df.info()

df.Gender.value_counts()

"""Handling Missing Values"""

df.Gender.mode()

df['Gender'] = df['Gender'].fillna('Male')

df.info()

"""Lable encoding"""

from sklearn import preprocessing

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['New'] = le.fit_transform(df.Gender.values)

df.head(3)

"""one_Hot Encoding"""

one_hot = pd.get_dummies(df['Geography'])

one_hot

df_dummies = pd.get_dummies(df)
df_dummies.head(4)

df = pd.read_csv('/content/CustomerChurn.csv')
df

df.shape

df.columns.values

df.dtypes

df.describe()

df['Churn'].value_counts()

df['Churn'].value_counts()/len(df)*100

df['Churn'].value_counts().plot(kind ='barh',figsize= (5,6) )
plt.xlabel('Count')
plt.ylabel('Table Variable')
plt.title( "Churn Table" , y =1.02)

"""##Data Cleaning"""

new_df= df.copy()

"""total charge should be numeric amount"""

new_df.info()

new_df

new_df.TotalCharges = pd.to_numeric(new_df.TotalCharges , errors = 'coerce')

new_df.isnull().sum()

new_df.info()

"""messing value treatment
## since % of messing values are very low
"""

#remove messing values
new_df.dropna(inplace = True)
#or
new_df.dropna(how ='any', inplace = True)

new_df.isnull().sum()

"""## divide customers into bins based on tanure eg (<12 months , 1-12 months , etc"""

labels = ["{0} - {1}".format(i, i+11) for i in range(1,72,12)]
new_df['Tanure_group'] = pd.cut(new_df.tenure, range(1,80,12), right = False, labels = labels)

new_df['Tanure_group'].value_counts()

"""##step 6 : remove column which are not required for processing"""

new_df.drop(columns= ['customerID','tenure'], axis = 1, inplace = True)

new_df

"""## univariate Analysis"""

for i, predictor in enumerate(new_df.drop(columns = ['Churn','TotalCharges','MonthlyCharges'])):
    plt.figure(i)
    sns.countplot(data = new_df , x = predictor , hue = 'Churn')

"""##Numerical Analysis"""

new_df['gender'].value_counts()

new_df_target0 = new_df[new_df["Churn"] =='No']
new_df_target1 = new_df[new_df["Churn"] =='Yes']

new_df_target1.gender.value_counts()

pd.crosstab(new_df.PaymentMethod, new_df.Churn)

"""##Bivarient Anaysis

convert yes and no into 1 & 0
"""

new_df['Churn'] = np.where(new_df.Churn =='Yes',1,0)

new_df.head()

import pandas as pd
import numpy as np

new_df= df.copy()

new_df_dummies = pd.get_dummies(new_df)
new_df_dummies.head()

Mth = sns.kdeplot(new_df_dummies.MonthlyCharges[(new_df_dummies["Churn"] == 0)],color = "Red",fill = True)
Mth = sns.kdeplot(new_df_dummies.MonthlyCharges[(new_df_dummies["Churn"] == 1)],ax = Mth,color ="Blue",fill = True)
Mth.legend(["No Churn","Churn"],loc ='upper right')
Mth.set_ylabel('Density')
Mth.set_xlabel('Monthly Charges')

plt.figure(figsize=(20,8))
new_df_dummies.corr()['Churn'].sort_values(ascending=False).plot(kind = 'bar')

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,12))
sns.heatmap(new_df_dummies.corr(),cmap = "Paired")



"""##PROJECT 1 - BANKING

"""

import seaborn as sns

import pandas as pd
df = pd.read_csv('/content/Banking.csv')

df.info()

import numpy as np
import matplotlib.pyplot as pit

df.shape

df.describe()

"""# Numerical data to catagorical Data
making a bin of incomes(0 - 20,000 , 20001 - 40,000)
"""

bins = [0,100000,300000,float('inf')]
lables = ['Low' , 'Med' , 'High']
df['Income_bin']  = pd.cut(df['Estimated Income'], bins=bins , labels=lables , right = False)

df.info()

df['Income_bin'].value_counts().plot(kind = 'bar')

# Examine the distribution of unique categories in categorical columns

# List of categorical columns
categorical_cols = ["BRId", "GenderId", "IAId", "Amount of Credit Cards",
                    "Nationality", "Occupation", "Fee Structure", "Loyalty Classification"]

# Loop through each categorical column and display value counts
for col in categorical_cols:
    print(f"\nValue Counts for '{col}':")
    display(df[col].value_counts())

"""#Bivarient analysis

"""

for i, predictor in enumerate(df.drop(columns = ['Income_bin','IAId','GenderId','BRId','Name','Client ID'])):
    pit.figure(i)
    sns.countplot(data = df , x = predictor, hue = 'Income_bin')

"""#Histoplot of value count for diferent occupation

"""

import matplotlib.pyplot as plt
import seaborn as sns

for col in categorical_cols:
    if col == "Occupation":   # corrected typo
        continue
    plt.figure(figsize=(8, 4))
    sns.countplot(x=df[col])  # better for categorical variables
    plt.title(f'Count Plot of {col}')
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.xticks(rotation=45)   # rotate labels if long names
    plt.show()

# univarient analysis
numarical_col = ['Estimated Income', 'Superannuation Savings']
plt.figure(figsize=(15,10))
for i,col in enumerate(numarical_col):
  plt.subplot(2,1,i+1)
  sns.histplot(df[col],kde = True)
  plt.title(col)
  plt.show()

"""#heat map"""

numerical_cols = ['Estimated Income', 'Superannuation Savings',
                  'Credit Card Balance', 'Bank Loans', 'Bank Deposits',
                  'Checking Accounts', 'Saving Accounts']
corelation_matrix = df[numerical_cols].corr()
plt.figure(figsize =(12,12))
sns.heatmap(corelation_matrix,annot = True,cmap = 'crest',fmt = ".2f")
plt.title("corelation Matrix")
plt.show()



















